### ISSUE TITLE
Unable to start Steam - network issues

### ISSUE THREAD

**Issue by ConsularParadi** [games-on-whales/wolf#120]
I am unable to start steam even after letting the container run overnight to download all dependencies. While checking the logs, the problem seems to be an <b>ssl certificate error</b>. I am attaching the [logs](https://pastebin.com/FGRi2rVml) for your reference.

**Comment by justforlxz** [comment]
I have another problem, I can launch steam, but in wizard mode, after selecting network, I can't go to the next step. The prompt is similar to low battery, unable to complete the update, and then quickly returns to the network mode.

**Comment by justforlxz** [comment]
> I have another problem, I can launch steam, but in wizard mode, after selecting network, I can't go to the next step. The prompt is similar to low battery, unable to complete the update, and then quickly returns to the network mode.

Looks like there is something wrong with my network.

**Comment by Murazaki** [comment]
Some people have reported issues on network because of resource hogging for instance on rendering. Make sure you have a proper setup that allows to run wolf (nvidia drivers > 530, preferably 550 and not 560).

**Comment by alibell** [comment]
I have exactly the same issue, stuck in steam big picture wizard screen.
I have the recommanded version of nvidia drivers and nvidia container kit.

I only managed to bypass that by logging to my steam account from my computer. To do so, I created a symbolic link of my wolf steam directory to my home directory :

```
# If you have an existing steam installation, backup it
mv ~/.local/share/Steam ~/.local/share/Steam.backup
ln -s /etc/wolf/CLIENT_ID/Steam/.steam/debian-installation ~/.local/share/Steam
```

Then login to Steam threw you desktop computer.
Finally, if you want to go back to your local steam setting :

```
unlink ~/.local/share/Steam && mv ~/.local/share/Steam.backup ~/.local/share/Steam
```

**Comment by alibell** [comment]
Also, I advise you to cap your download speed on Steam, otherwise if you have a good connection you would have some issue with streaming while downloading game

**Comment by justforlxz** [comment]
> I have exactly the same issue, stuck in steam big picture wizard screen. I have the recommanded version of nvidia drivers and nvidia container kit.
> 
> I only managed to bypass that by logging to my steam account from my computer. To do so, I created a symbolic link of my wolf steam directory to my home directory :
> 
> ```
> # If you have an existing steam installation, backup it
> mv ~/.local/share/Steam ~/.local/share/Steam.backup
> ln -s /etc/wolf/CLIENT_ID/Steam/.steam/debian-installation ~/.local/share/Steam
> ```
> 
> Then login to Steam threw you desktop computer. Finally, if you want to go back to your local steam setting :
> 
> ```
> unlink ~/.local/share/Steam && mv ~/.local/share/Steam.backup ~/.local/share/Steam
> ```

You can add the STEAM_STARTUP_FLAGS=-steamos3 environment variable to steam in wolf's config.toml to disable bigpicture mode, complete the login in desktop mode, and then delete the environment variable to restore bigpicture mode.

https://github.com/games-on-whales/gow/blob/4c4ca4f004c1f0a5694fc1c236460cc60902aa99/images/steam/scripts/startup.sh#L12C23-L12C67

**Comment by alibell** [comment]
Oh thanks, this is way easier this way

**Comment by PierreBeucher** [comment]
I have the same issue (stuck on network selection and yellow text showing an "update" before rolling back), I did the same workaround described by @justforlxz to make it work.

BTW I created this Discord thread before seeing this issue: https://discord.com/channels/856434175455133727/1284532285655220245

The same problem happens using older Steam and Wolf image version, so it may be something with internal Steam update (the one downloaded on startup before showing main screen)

**Comment by TheRainstorm** [comment]
> I have another problem, I can launch steam, but in wizard mode, after selecting network, I can't go to the next step. The prompt is similar to low battery, unable to complete the update, and then quickly returns to the network mode.

I have the same problem, but I found you can pass it by clicking wired connection twice quickly

**Comment by ABeltramo** [comment]
I've ended up removing the `bigpicture` flag from the defaults in https://github.com/games-on-whales/gow/commit/ba0bc43faa019daeb146fac759e7a5a9d351ecd5

You can always put it back in by modifying the `config.toml` or just enter bigpicture manually when starting the container.
