### ISSUE TITLE
weird behavior of mouse click

### ISSUE THREAD

**Issue by AnakTeka** [games-on-whales/wolf#130]
I exclusively use Wolf with mouse, and I have noticed a weird interaction of the mouse click.

Based on my observation, a mouse click will only be registered IF i move my mouse after i click.

https://github.com/user-attachments/assets/19a2c16f-570a-46de-a348-4ac163ee9c76

https://github.com/user-attachments/assets/967bc44e-1b8b-46b5-8f32-e51fe18f1a35

I created a simple web to explain this behavior, the first video is where i demonstrate the weird behavior in Wolf environment.

Notice that after I click the mouse the web output nothing and the click is registered only after i move the mouse (on the video i use the monitor as the mouse surface to move the mouse). 
Compare the behavior with the second video where the mouse click is registered right after.

Hopefully I'm making sense, let me know if further clarification is needed!

**Comment by ABeltramo** [comment]
I think I know what the issue is, I'm just leaving a note here; I'll test it out tomorrow.

We are missing a call to

```rust
pointer.frame()
```
in [here](https://github.com/games-on-whales/gst-wayland-display/blob/5812a3b7a2686f1ed38bd821c8a1fd98dc804abc/wayland-display-core/src/comp/input.rs#L253).

**Comment by ABeltramo** [comment]
I can replicate your issue and it should be fixed in https://github.com/games-on-whales/wolf/pull/121 you can give it a go by pulling 
```
ghcr.io/games-on-whales/wolf:dev-mouse-sensitivity
```
feel free to re-open if that doesn't fix it!

**Comment by AnakTeka** [comment]
awesome! Can confirm it is fixed in `wolf:dev-mouse-sensitivity`
