### ISSUE TITLE
Time zone

### ISSUE THREAD

**Issue by csrednicki** [games-on-whales/wolf#137]
Hi, first of all thank you for this great gaming solution :) Second, I want to set my timezone correctly. Currently it is showing like this:
![image](https://github.com/user-attachments/assets/44f7a80d-eedb-4495-919d-ae2a01650d1d)
which is two hours late compared to my local time.
How can I change time zone (Europe/Poland) using docker compose file ?

**Comment by ABeltramo** [comment]
Timezone should be as simple as setting the `TZ` env variable, ex:
```
docker run -e TZ=Europe/Warsaw --rm -it --entrypoint date ghcr.io/games-on-whales/base-app:edge
Wed Oct  9 21:21:56 CEST 2024
```

You'll have to set this additional env variable in all the apps defined in your `config.toml`, see the docs linked below on how to do it.

The `us` there in your screenshot refers to the keyboard layout instead, you can see how to change that in the [docs](https://games-on-whales.github.io/wolf/stable/user/configuration.html#_changing_and_switching_keyboard_layouts_in_wolf_apps_containers).

Feel free to re-open if this doesn't work!

**Comment by csrednicki** [comment]
Hi, @ABeltramo thanks for quick reply. I followed your instructions but it worked half part. Below is my definition of Steam application with added TZ env var and screenshot when it was running with opened shell window.
![image](https://github.com/user-attachments/assets/c4747d36-1a18-46a5-8420-e1f064599b7f)
As you see shell is recognizing changed time zone but Sway is not. I'm guessing TZ env variable is not passed to Sway correctly.

```
[[apps]]
start_virtual_compositor = true
title = "Steam"

[apps.runner]
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN"],
    "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
    "Ulimits": [{"Name":"nofile", "Hard":10240, "Soft":10240}],
    "Privileged": false,
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
"""
ports = []
devices = []
env = [
  "PROTON_LOG=1",
  "TZ=Europe/Warsaw",
  "RUN_SWAY=true",
  "GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*",
]
mounts = []
image = "ghcr.io/games-on-whales/steam:edge"
name = "WolfSteam"
type = "docker"
```

**Comment by csrednicki** [comment]
@ABeltramo Cannot reopen this issue. I see only comment button.

**Comment by ABeltramo** [comment]
Sorry about that, I'll look into it. We are probably missing a call to `tzselect` somewhere..

**Comment by ABeltramo** [comment]
This turned out to be a specific issue with Waybar clock, I've applied [this workaround](https://github.com/Alexays/Waybar/issues/3575#issuecomment-2338813343) for now.

You should be able to test it out by just updating the images using:
```
docker pull ghcr.io/games-on-whales/steam:edge
```
