### ISSUE TITLE
Changing title in config.toml leads to non function of app entry

### ISSUE THREAD

**Issue by Skerga** [games-on-whales/wolf#144]
I tried creating a direct launcher for games using the Lutris config as base, everything works so far except the moment i change the title in my config it breaks and the app wont get started.

this is the used config entry:
```
[[apps]]
icon_png_path = '/etc/wolf/shared/lutris/share/covers/paper-mario-the-thousand-year-door.png'
start_virtual_compositor = true
title = 'Lutris'

    [apps.runner]
    base_create_json = '''{
  "HostConfig": {
    "IpcMode": "host",
    "CapAdd": ["NET_RAW", "MKNOD", "NET_ADMIN", "SYS_ADMIN", "SYS_NICE"],
    "Privileged": false,
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
'''
    devices = []
    env = [ 'RUN_SWAY=1', 'GOW_REQUIRED_DEVICES=/dev/input/event* /dev/dri/* /dev/nvidia* /var/lutris/', 'XKB_DEFAULT_LAYOUT=de', 'LUTRIS_ARGS=lutris:rungame/paper-mario-the-thousand-year-door']
    image = 'ghcr.io/games-on-whales/lutris:edge'
    mounts = [ '/etc/wolf/shared/lutris:/var/lutris/:rw', '/etc/wolf/shared/ryujinx:/home/retro/.config/Ryujinx/:rw' ]
    name = 'WolfLutrisGameLauncher'
    ports = []
    type = 'docker'
```
here a small video of the whole thing:
https://github.com/user-attachments/assets/1db37863-c410-452e-8446-9e869cae4d4a

here the backtrace:
[dump.zip](https://github.com/user-attachments/files/17689445/dump.zip)

**Comment by csrednicki** [comment]
If you change title you need to also change corresponding folder name in `/etc/wolf/<userid>/<title>`.

**Comment by ABeltramo** [comment]
Thanks @csrednicki that was indeed the issue, we've discussed this in Discord with @Skerga  so I'll close this here.
