### ISSUE TITLE
Multiple steam games now crashing shortly after starting as of sha-a5f56e2

### ISSUE THREAD

**Issue by jefflewis** [games-on-whales/wolf#145]
After pulling the latest wolf container image, I’ve seen multiple steam games freeze and crash the process with the last log entry being 

```
boost: mutex lock failed in pthread_mutex_lock: Invalid argument.
```

Wolf itself restarts after this error, but the Steam app has exited and the moonlight connection is dead.

The current image I have is latest,  stable and the image I was running previously and did not see these issues was published 4 days ago (sha-018e1dd). 

I switched the image tag from stable back to the previous sha and the games that had been crashing run fine. It seems like something from the past two days is causing some kind of hard exception that was not previously.

**Comment by ABeltramo** [comment]
I've just pushed a potential fix (although I couldn't reliably replicate your issue), let me know if latest `:stable` fixes it for you.  
If not, could you please send the full Wolf logs when the exception happens?

**Comment by jefflewis** [comment]
I ran a quick test on one of the games that had been crashing after re-pulling latest and it seemed to work! Nice job! :D
