### ISSUE TITLE
How to use without a GPU?

### ISSUE THREAD

**Issue by gregoryking** [games-on-whales/wolf#153]
I'm running wolf in docker on a Debian host with no GPU (neither dedicated card nor onboard graphics). I'm running the  compose file from the docs and getting the following error when running anything other than the Test ball app (which runs fine):

```
wolf  | 19:53:22.294313227 DEBUG | Host app state folder: /etc/wolf/1143853187824259421/RetroArch, creating paths
wolf  | 19:53:22.294370926 DEBUG | [STREAM_SESSION] Create wayland compositor
wolf  | 19:53:22.294385935 DEBUG | [WAYLAND] Creating wayland display
wolf  | 2024-11-25T19:53:22.296720Z ERROR libgstwaylanddisplay: Failed to create wayland display. err=Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })

```

Should this be working for my setup, is there extra config I need in my compose file or host?

**Comment by ABeltramo** [comment]
You'll have a hard time running games without a GPU, and we really are gaming focused. With that said, you could still try running stuff with SW (CPU only) acceleration by adding the env variable

```
WOLF_RENDER_NODE=software
```

**Comment by gregoryking** [comment]
Thank you for the speedy reply, much appreciated. Worked a treat 👍
