### ISSUE TITLE
Steam - "Verifying installation" status/screen never finishes

### ISSUE THREAD

**Issue by handtrixx** [games-on-whales/wolf#157]
Hi,
First at all: I love the wolf project! You did a more than amazing job here.
Sincereley since some weeks I have the issue, which even reapears after a clean setup: When starting Steam the "Verifying installation" status/screen never finishes. To get there I had to switch the config to gamscope RUN_GAMESCOPE=true but the rest of my settings is pretty the standard.
Am I the only one facing this issue?

the log output of the steam container is:
[2024-12-15 13:06:10] 
[2024-12-15 13:06:10] [ /etc/cont-init.d/10-setup_user.sh: executing... ]
[2024-12-15 13:06:10] **** Configure default user ****
[2024-12-15 13:06:10] Setting default user uid=1000(retro) gid=1000(retro)
userdel: ubuntu mail spool (/var/mail/ubuntu) not found
useradd: warning: the home directory /home/retro already exists.
useradd: Not copying any file from skel directory into it.
[2024-12-15 13:06:10] Setting umask to 000
[2024-12-15 13:06:10] Ensure retro home directory is writable
[2024-12-15 13:06:10] Ensure XDG_RUNTIME_DIR is writable
[2024-12-15 13:06:10] DONE
[2024-12-15 13:06:10] 
[2024-12-15 13:06:10] [ /etc/cont-init.d/15-setup_devices.sh: executing... ]
[2024-12-15 13:06:10] **** Configure devices ****
[2024-12-15 13:06:10] Exec device groups
[2024-12-15 13:06:10] Path '/dev/input/*' is not present.
[2024-12-15 13:06:10] Adding user 'retro' to groups: sgx,video
[2024-12-15 13:06:10] DONE
[2024-12-15 13:06:10] 
[2024-12-15 13:06:10] [ /etc/cont-init.d/30-nvidia.sh: executing... ]
[2024-12-15 13:06:10] 
[2024-12-15 13:06:10] 
[2024-12-15 13:06:10] [ /etc/cont-init.d/init-gamescope.sh: executing... ]
[2024-12-15 13:06:10] **** Setting up Gamescope ****
[2024-12-15 13:06:10] 
[2024-12-15 13:06:10] [ /etc/cont-init.d/system-services.sh: executing... ]
*** DBus started ***
*** Bluez started ***
bluetoothd[83]: Bluetooth daemon 5.72
bluetoothd[83]: src/adapter.c:adapter_init() Failed to access management interface
bluetoothd[83]: src/main.c:main() Adapter handling initialization failed
*** NetworkManager started ***
[2024-12-15 13:06:10] Launching the container's startup script as user 'retro'
[2024-12-15 13:06:10] Starting Steam with DISPLAY=
Claimed global gamescope stats session at "/tmp/sockets/gamescope-stats"
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
wlserver: [backend/headless/backend.c:68] Creating headless backend
Couldn't open plugin directory: No such file or directory
No plugins found, falling back on no decorations
vulkan: selecting physical device 'AMD Radeon Graphics (RADV GFX1103_R1)': queue family 1
vulkan: physical device supports DRM format modifiers
vulkan: supported DRM formats for sampling usage:
vulkan:   AR24 (0x34325241)
vulkan:   XR24 (0x34325258)
vulkan:   AB24 (0x34324241)
vulkan:   XB24 (0x34324258)
vulkan:   NV12 (0x3231564E)
vulkan:   AB4H (0x48344241)
vulkan:   XB4H (0x48344258)
vulkan:   AB48 (0x38344241)
vulkan:   XB48 (0x38344258)
vulkan:   AB30 (0x30334241)
vulkan:   XB30 (0x30334258)
vulkan:   AR30 (0x30335241)
vulkan:   XR30 (0x30335258)
wlserver: Running compositor on wayland display 'gamescope-0'
wlserver: [backend/headless/backend.c:16] Starting headless backend
wlserver: [xwayland/sockets.c:118] Created /tmp/.X11-unix ourselves -- other users will be unable to create X11 UNIX sockets of their own
wlserver: [xwayland/server.c:108] Starting Xwayland on :0
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
wlserver: [types/wlr_compositor.c:681] New wlr_surface 0x643aae3e2230 (res 0x643aae3e2130)
wlserver: [xwayland/server.c:273] Xserver is ready
xwm: Failed to load host cursor. Falling back to left_ptr.
steam.sh[157]: Running Steam on ubuntu 24.04 64-bit
steam.sh[157]: STEAM_RUNTIME is enabled automatically
setup.sh[207]: Steam runtime environment up-to-date!
wlserver: [types/wlr_compositor.c:681] New wlr_surface 0x643aae5a4600 (res 0x643aae4aecf0)
[2024-12-15 13:06:11.164] [info] [config.cpp:123] parsing config: '/tmp/mangohud.I6Uo8Xyk'
[2024-12-15 13:06:11.181] [info] [overlay.cpp:808] Uploading is disabled (permit_upload = 0)
xwm: Rejecting WM_CHANGE_STATE to ICONIC for window 0x400007
wlserver: [types/wlr_compositor.c:681] New wlr_surface 0x643aae5a4960 (res 0x643aae3e6a30)
xwm: got the same buffer committed twice, ignoring.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
dbus-daemon[156]: [session uid=1000 pid=156] Activating service name='org.freedesktop.portal.IBus' requested by ':1.0' (uid=1000 pid=295 comm="/home/retro/.steam/debian-installation/ubuntu12_32" label="steam (unconfined)")
dbus-daemon[156]: [session uid=1000 pid=156] Successfully activated service 'org.freedesktop.portal.IBus'

my app config is
[[apps]]
start_virtual_compositor = true
title = 'Steam'

    [apps.runner]
    base_create_json = '''{
  "HostConfig": {
    "IpcMode": "host",
    "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN"],
    "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
    "Ulimits": [{"Name":"nofile", "Hard":10240, "Soft":10240}],
    "Privileged": false,
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
'''
    devices = []
    env = [ 'PROTON_LOG=1', 'RUN_GAMESCOPE=true', 'GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/*', 'TZ=Europe/Berlin', 'XKB_DEFAULT_LAYOUT=de' ]
    image = 'ghcr.io/games-on-whales/steam:edge'
    mounts = []
    name = 'WolfSteam'
    ports = []
    type = 'docker'

i am using an amdgpu on a headless server

**Comment by ABeltramo** [comment]
Hi there! 👋
Thanks for the kind words, that's appreciated!

We've recently fixed a similar issue that was affecting Intel/AMD with a recent update to the Steam client. Have you already tried downloading the latest version with:
```
docker pull ghcr.io/games-on-whales/steam:edge
```
and restarting Wolf?

(Make sure to put back the default env variables in `config.toml` too)

**Comment by handtrixx** [comment]
Wow, thanks for the quick response on a sunday!

Now, i feel stupid, the "docker pull ghcr.io/games-on-whales/steam:edge" was enough to make it work again with the standard config! 
Somehow I didn't think of that if i do a normal docker compose pull, it will only update the wolf container image itself but not not the related apps in use. ouch... Maybe that's worth to notice in the documentation for others as stupid like me.
So, a thousand thanks again!

btw.: if you need support with the documentation or in writting fancy react UIs, I would love to help you out.

**Comment by ABeltramo** [comment]
> Somehow I didn't think of that if i do a normal docker compose pull, it will only update the wolf container image itself but not not the related apps in use. ouch...

Yeah, you definitely aren't the first one to fall into that trap; I should really find a better way to bake that into Wolf.. At the very least print out a warning if there's a new version of some app available.

I'll take all the help that I can get, PRs are very much welcome here!

P.S. there's a UI [in the works](https://github.com/games-on-whales/wolf/issues/80#issuecomment-2318715619) but I've been sidetracked by other interesting things in the meantime, stay tuned! 😉
