### ISSUE TITLE
is there a way to do a hybrid approach to client folders, where there can be multiple users with their own games, but each user can be using different clients that have access to the same games?

### ISSUE THREAD

**Issue by ghost** [games-on-whales/wolf#158]
Like say sometimes I'll connect from my come computer, but then later I'll want to connect from a device connected to my TV. While still sharing with other users, who may have more then one client they also use. could this be done with a login screen, which can be skipped on devices with only one user, and a simple pin for shared devices? then each user could have their own game folders

**Comment by ABeltramo** [comment]
Not yet, but it has been discussed at lengths in the past, and it's definitely in progress, see [here](https://github.com/games-on-whales/wolf/issues/80#issuecomment-2318715619).  
Stay tuned! 😉
