### ISSUE TITLE
Bug/Error: Cannot Pair wtih Moonlight app (key not found)

### ISSUE THREAD

**Issue by RandomNinjaAtk** [games-on-whales/wolf#30]
Followed the instructions here (docker run): https://games-on-whales.github.io/wolf/stable/user/quickstart.html

When attempting connect a Moonlight client, I successfully get the webpage to input the key and receive the following error:

![image](https://github.com/games-on-whales/wolf/assets/8386416/cf8efc6c-b972-4fcf-bfb7-e5a092f2dca0)

**Comment by ABeltramo** [comment]
Thanks for checking out Wolf! 

Have you removed the `#...` part of the URL by any chance? That's a temporary key needed in order to avoid anyone to be able to pair with the instance.

**Comment by RandomNinjaAtk** [comment]
So the url would look like this: http://x.x.x.x:47989/pin/ ?

If that is the case, I did try that and got the same error message

**Comment by ABeltramo** [comment]
Wolf will log a line with a full URL everytime that you try to pair, example: `http://localhost:47989/pin/#337327E8A6FC0C66`

You need to put the full URL with the additional `#...` in the address bar in order to successfully pair.

**Comment by RandomNinjaAtk** [comment]
> Wolf will log a line with a full URL everytime that you try to pair, example: `http://localhost:47989/pin/#337327E8A6FC0C66`
> 
> You need to put the full URL with the additional `#...` in the address bar in order to successfully pair.

That did work! Guess it helps if I fully read.... 

Thanks for your time, the PR I opened should be a valid fix though..
