### ISSUE TITLE
Browser steaming

### ISSUE THREAD

**Issue by ghost** [games-on-whales/wolf#36]
Is streaming games through the browser possible with this repo? As for moonlight the closest thing to that is Moonlight for ChromeOS but is there anything on the browser like what webRTC could? Thank you.

**Comment by ABeltramo** [comment]
Right now Wolf only supports Moonlight, but I'm working on #32 in order to be able to support WebRTC and browser based sessions. 

Stay tuned! 😉

**Comment by ghost** [comment]
Haha, awesomeee. Would that become similar to selkies-gstreamer then? Also WebTransport is rolling out.

**Comment by ABeltramo** [comment]
That looks like a cool project, I didn't knew about it!  
I guess we'll have Gstreamer in common but we (try to) automate the "setting up a virtual desktop" part + games and apps which seems to be left out there, or at least, that's my impression by just skimming thru the readme.

**Comment by ghost** [comment]
Do check out the other repositories by selkies then, they might be interesting to you too as they do have a docker desktop repo although its got no pulse anymore.

**Comment by ghost** [comment]
Also, one of their devs ehfd made this cool project https://github.com/ehfd/nvidia-dind .
Games on whales on whales 😂
