### ISSUE TITLE
Where do your games go?

### ISSUE THREAD

**Issue by AureliusGilchrist** [games-on-whales/wolf#63]
So, for example, for retroarch -- where do you put your games? I'm using docker-compose, and.. I've attempted to set up my games folder like so `/server/games/:/home/retro/` and yet, it doesn't show games in there -- but I suspect this is because of how complex GOW/Wolf is -- I'm still getting used to even docker, lol.

**Comment by ABeltramo** [comment]
By default, Wolf mounts your host `/etc/wolf/<MOONLIGHT_CLIENT_ID>/<APP_NAME>` into `/home/retro` unless you manually tweak stuff. You have two options here:
- You can copy the files down that default path, this will be visible only by one client; so for example connecting from the phone will see different files than connecting from a laptop
- You can add a path in the `mounts = []` option in the `config.toml` file, this will be shared by all clients.  Example:
```toml
mounts = [
    "/mnt/ROMS/:/ROMS:rw" # will mount /mnt/ROMS from the host into /ROMS in the running app
]
```

**Comment by AureliusGilchrist** [comment]
Alright sweet -- many thanks! I also do have a bug, but I'll make a separate thread about that -- I still need to probe deeper on it and give the debug logs on it.

**Comment by AureliusGilchrist** [comment]
Whoop, forgot to close. My bad. Here you go

**Comment by ABeltramo** [comment]
Thanks, I'm testing out all the latest changes before making a release; please make sure to pull the latest `:stable` and check the latest quickstart guide. There's only one big change required compared to how it used to work: you have to mount `/etc/wolf:/etc/wolf:rw` (or whichever path the host app folder env variable is pointing to, if changing changing default).

Let me know if anything is broken!

**Comment by AureliusGilchrist** [comment]
> Thanks, I'm testing out all the latest changes before making a release; please make sure to pull the latest `:stable` and check the latest quickstart guide. There's only one big change required compared to how it used to work: you have to mount `/etc/wolf:/etc/wolf:rw` (or whichever path the host app folder env variable is pointing to, if changing changing default).
> 
> Let me know if anything is broken!

Will do! Thank you!
