### ISSUE TITLE
Crash when connecting from a public network

### ISSUE THREAD

**Issue by rty813** [games-on-whales/wolf#74]
When connecting from the local network, everything works fine and streaming is possible. Then I set up port forwarding on the router, mapping ports 47989, 47984, 47999, 48010, 48100-48110, 48200-48210, and 48000 to the public network. I can successfully pair through the public network, but wolf crashes when starting the stream.

![Screenshot_20240605_115951_Moonlight](https://github.com/games-on-whales/wolf/assets/22488813/dae517ff-7d46-4f0b-b9a7-e9c526820429)

[crash_log.txt](https://github.com/user-attachments/files/15572936/crash_log.txt)
[backtrace.2024-06-05-04-51-54.dump.zip](https://github.com/user-attachments/files/15572939/backtrace.2024-06-05-04-51-54.dump.zip)

**Comment by rty813** [comment]
After multiple retries, it occasionally works. However, after some time, it stops working again.

**Comment by ABeltramo** [comment]
I've just pushed an update that should fix the connection issue that has been recently reported by a few users. Make sure to update the Wolf Docker image by downloading the latest with:
```
docker pull ghcr.io/games-on-whales/wolf:stable
```
If that doesn't solve the issue, can you please post the full logs from Wolf?

**Comment by rty813** [comment]
It's much more stable now. I'll try it a bit more. Thank you very much!
