### ISSUE TITLE
[Question] How to mount the host directory to the app? 

### ISSUE THREAD

**Issue by rty813** [games-on-whales/wolf#76]
I have some game saves and game content that I want to mount to the Steam app.

**Comment by rty813** [comment]
After reviewing the source code, I found that the mount path are hardcoded except `app_state_folder` and there is no config provided for users to implement custom mounts.

**Comment by ABeltramo** [comment]
Quite the opposite, you can easily add additional mount points just by changing the config.toml file. There's also an example in the docs: https://games-on-whales.github.io/wolf/stable/user/configuration.html#_docker

**Comment by rty813** [comment]
Found it, thank you very much.
