### ISSUE TITLE
ARC A310 QSV extremely unreliable?

### ISSUE THREAD

**Issue by dragon2611** [games-on-whales/wolf#79]
Ubuntu 22.04, finding QSV is extremely unreliable for wolf with an ARC A310, note this is a VM with the GPU passed through so that could be impacting things.

Tried updating opencl but doesn't seem to help.

It looks like something might be crashing when trying to setup the stream as I can see some dump files in /etc/wolf/cfg, very occasionally (probably less than 1 in 10 attempts) it will work.

I removed the QSV sections from config.toml and fell back to vaapi and that seems a lot more consistent.

**Comment by ABeltramo** [comment]
Can you share some logs?   Unfortunately, I dont have an Intel GPU to test it out properly, quicksync is all based on user reports and the community..

**Comment by dragon2611** [comment]
@ABeltramo - I dont think I have the output from the docker console anymore, I did however (hopefully) send you over the backtrace files that got dumped in the /etc/wolf/cfg folder as well as the steam log from my session folder.

It's not a major problem for me if this doesn't work given the A310 is fairly weak GPU anyway and the machine it's in is meant to be a server not a gaming machine.

**Comment by ABeltramo** [comment]
After a bit of debugging I can reproduce the issue on my Intel ARC, seems to be the same as https://github.com/intel/media-driver/issues/1800 

Replacing `vapostproc` with `videoconvert` completely fixes it for me, see the change [here](https://github.com/games-on-whales/wolf/pull/91/commits/30cc222fc8353962e297595f998e01d75befe472#diff-50b9f6e642f6228851e9eeeb29ec64c78d5d9ee4677e4d884825a66a40d4570dL291-L306).

Fixed pipeline:
```toml
[[gstreamer.video.hevc_encoders]]
plugin_name = "qsv"
check_elements = ["qsvh265enc", "videoconvert"]
video_params = """
queue !
videoconvert !
video/x-raw, chroma-site={color_range}, width={width}, height={height}, format=NV12, colorimetry={color_space}
\
"""
encoder_pipeline = """
qsvh265enc b-frames=0 gop-size=0 idr-interval=1 ref-frames=1 bitrate={bitrate} rate-control=cbr low-latency=1 target-usage=6 !
h265parse !
video/x-h265, profile=main, stream-format=byte-stream
\
"""
```
