### ISSUE TITLE
Steam reinstalls when connecting

### ISSUE THREAD

**Issue by Leesam** [games-on-whales/wolf#87]
Steam seems to be reinstalling every time I connect (even from the same moonlight client). I have to choose language, time zone, sign in and then set up the library folder each time I choose Steam from moonlight. After re-performing the setup, games work _very well_. I'd just like the steam client to persist across connections.

It looks like the /home/retro folder mounted to app_state_folder/Steam/ is not copying any hidden folders of files. 

While steam is running i can look at the /home/retro folder and see many files which aren't available on the datastore.

![SteamDocker](https://github.com/user-attachments/assets/5b529f11-1225-4a60-9dcd-af7b1669d8ff)

![DatastoreView](https://github.com/user-attachments/assets/5becf2d2-e0b2-47e3-8cfd-003f07a290f1)

**Comment by ABeltramo** [comment]
Sounds like there's something wrong going on with the folder mounts..
Can you share the exact command or docker-compose.yml that you use to start Wolf?   
Have you changed anything from the quickstart guide?

**Comment by Leesam** [comment]
I just managed to resolve the issue after reading the docs again.

I had changed the HOST_APPS_STATE_FOLDER volume but not in the environment variable to match. The docker host is an unraid machine so /etc/wolf folder the steam container was using was temporary and getting wiped each reboot.

**Comment by ABeltramo** [comment]
I'm glad it's sorted, have fun!
