### ISSUE TITLE
Feature Request: Support for Podman

### ISSUE THREAD

**Issue by robedpixel** [games-on-whales/wolf#89]
As a user who prefers to use Podman to run containers, would it be possible to extend wolf to use Podman for its functionality instead of docker?

**Comment by ABeltramo** [comment]
Everything should work already. Have you encountered any specific issue?

**Comment by robedpixel** [comment]
No specific issue, I assumed that since the docs only mentioned compatibility with docker, that meant that it wasn't tested with other container runtimes. I will be closing the issue now.
