### ISSUE TITLE
metadata.pegasus.txt launch command path

### ISSUE THREAD

**Issue by screwyse** [games-on-whales/wolf#94]
Hi,

Before everything, thanks for the amazing job. Wolf is exactly what I needed.

But I have a problem with the launch command in the metadata.pegasus.txt.
I can launch Pegasus and it works well.
The applications like RetroArch and standalone emulator work well too.
I can launch games and play them perfectly through the applications but when I want to configure the metadata.pegasus.txt to have a more user friendly experience in Pegasus, to use collections for example, I have to configure the launch command line and here is my problem.

According to the Pegasus docs, the command should be something like : (directory of retroarch folder)/retroarch.exe -L (directory of retroarch folder)/cores/(exact name and extension of core needed, eg, fbneo_libretro.dll) {file.path}

This is for windows, for a linux environment I have found the core.so to replace the core.dll but I don't know by which file I have to replace the retroarch.exe

My question is : How does Pegasus to launch retroarch, and more globaly how does wolf to launch Pegasus or Steam or RetroArch etc...

Thanks in advance.

**Comment by ABeltramo** [comment]
Thanks for the kind words, I'm glad you like this project!

> How does Pegasus to launch retroarch, and more globaly how does wolf to launch Pegasus or Steam or RetroArch etc...

I get your pain, I should really spend some time writing this down better in the docs.. In the meantime I can give you some tips!

The default `metadata.pegasus.txt` lives inside the container at the path `/cfg/app/metadata.pegasus.txt`, [here you can read the default content](https://github.com/games-on-whales/gow/blob/master/images/pegasus/configs/app/metadata.pegasus.txt).  
The other very important file is `https://github.com/games-on-whales/gow/blob/b410c993c31bba1fe97be10960056d3b1df85890/images/pegasus/configs/app/game_dirs.txt`, by default we'll expect ROMs to be mounted under `/ROMs/`. You can add that path in the Wolf `config.toml` (by default it'll be in your host under `/etc/wolf/cfg/config.toml`), look for the `Pegasus` entry and then add your mount under `mounts`, ex:

```toml
[apps.runner]
type = "docker"
name = "WolfPegasus"
image = "ghcr.io/games-on-whales/pegasus:edge"
mounts = [
  "/mnt/PATH_TO_ROMS_IN_YOUR_HOST/:/ROMs/:rw" # <-- EDIT HERE
]
```
Hope this helps, if you get a bit more specific on what you are trying to do I can probably help you better.

**Comment by screwyse** [comment]
> The default `metadata.pegasus.txt` lives inside the container at the path `/cfg/app/metadata.pegasus.txt`, [here you can read the default content](https://github.com/games-on-whales/gow/blob/master/images/pegasus/configs/app/metadata.pegasus.txt).

Thank you so much, it works pefectly.
The only thing I missed was the default content. If someone need help, here is an example : 

According to the Pegasus docs the launch command have to be something like : 

(directory of retroarch folder)/retroarch.exe -L (directory of retroarch folder)/cores/(exact name and extension of core needed, eg, fbneo_libretro.dll) {file.path}

For example you want to launch a Snes game with RetroArch, then the command to put in a metadata.pegasus.txt (check pegasus docs) is :

launch:  "/usr/bin/retroarch" -L "/home/retro/.config/retroarch/cores/mednafen_supafaust_libretro.so" "{file.path}"

Check [here](https://github.com/games-on-whales/gow/blob/master/images/pegasus/configs/app/metadata.pegasus.txt) to know the default content of the application and for the core you have to choose which you want in the cores directory, it must be a .so file.
